DROP TABLE IF EXISTS TASK;

CREATE TABLE TASK (
                      ID BIGINT AUTO_INCREMENT NOT NULL,
                      STATUS VARCHAR(64) NOT NULL,
                      TITLE VARCHAR(128) NOT NULL,
                      DESCRIPTION VARCHAR(512) NOT NULL,
                      DUE_DATE DATE,
                      CREATED_AT TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
                      PRIMARY KEY (ID)
);